<?php

namespace AppBundle\Repository;

/**
 * FoodsaverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodsaverRepository extends \Doctrine\ORM\EntityRepository
{
}
