app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
  path: /api/v1/logout

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs